### PR TITLE
Add example and command for controll intercom locks

### PR DESCRIPTION
**Pull request by grimpy**
Signed-off-by: Jo De Boeck <deboeck.jo@gmail.com>

### CODE REVIEW

**Comment by grimpy** [comment]
This is based on https://stackoverflow.com/questions/68292303/c-sharp-marshaling-c-functions

a lot of placed on the internet you can only find unlocking of the door through isapi request which is is missing on some devices

**Comment by laszlojakab** [comment]
Hello @grimpy Thanks for the PR! I have tested your modification but I can't confirm it is working because my device returned `error code 23 (Device does not support this function)`. If someone can confirm that it is a working example I can merge it. 
@pergolafabio could you please check it?

**Comment by pergolafabio** [comment]
I already did, and added this to my addon,... So it works :-)

**Comment by grimpy** [comment]
Maybe with you it's a diffrent lock id, but I've been using this since I made this PR and it works fine for me

**Comment by laszlojakab** [comment]
I had some time now to upgrade my doorbell to the latest firmware and test this PR again and works. Thanks for the contribution.

**Comment by pergolafabio** [comment]
nice @laszlojakab 

i have also another example, to send ISAPI commands with SDK
take a look at this file/example:

https://github.com/pergolafabio/Hikvision-Addons/blob/main/hikvison-sdk/hik_isapi.py

**Pull request merged**
